version: 2

models:
  - name: stg_orders
    description: "Cleaned orders table"

    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null


  - name: stg_customers
    description: "Cleaned customers table"

    columns:
      - name: customer_id
        tests:
          - not_null
          - unique


  - name: stg_products
    description: "Cleaned products table"

    columns:
      - name: product_id
        tests:
          - not_null
          - unique


  - name: fct_orders
    columns:
      - name: order_date
        tests:
          - not_null